# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Gather instance information
  ansible.builtin.import_tasks: tasks/get_instance_ids.yml

- name: Report if no instances found
  ansible.builtin.debug:
    msg: "No instances found with label ghpc_deployment={{ deployment_name }} in project {{ project }}."
  when: instances | length == 0

- name: Set up variables for preemption query
  ansible.builtin.set_fact:
    gce_instances_list: "{{ instances.stdout | default('[]') | from_json }}"
    query_window: "4h" # How far back to look for preemptions

# Creating a filter string of the form "resource.labels.instance_id=id1 OR resource.labels.instance_id=id2"
- name: Build instance ID filter string
  ansible.builtin.set_fact:
    instance_id_filter: "{{ gce_instances_list | map(attribute='id') | map('regex_replace', '^(.*)$', 'resource.labels.instance_id=\"\\1\"') | join(' OR ') }}"
  when: gce_instances_list | length > 0

- name: Query Cloud Audit Logs for any preemption events for these nodes
  ansible.builtin.shell: |
    gcloud logging read '
      resource.type="gce_instance"
      AND protoPayload.methodName="compute.instances.preempted"
      AND log_id("cloudaudit.googleapis.com/system_event")
      AND ({{ instance_id_filter }})
    ' --project={{ project }} --freshness={{ query_window }} --format="json"
  register: preemption_logs
  when: instance_id_filter is defined and instance_id_filter != ""

- name: Parse preemption logs
  ansible.builtin.set_fact:
    preemption_logs_parsed: "{{ (preemption_logs | default({})).get('stdout', '[]') | from_json }}"

- name: Display Instance Names being checked
  ansible.builtin.debug:
    msg: "Instance Names being checked for preemption in {{ deployment_name }}: {{ gce_instances_list | map(attribute='name') | list }}"
  when: gce_instances_list | length > 0

# Displays preempted nodes if any, else, gives message that no preemption events found
- name: Report preemption status
  ansible.builtin.debug:
    msg: >-
      {% if preemption_logs_parsed | length > 0 %}
      Preemption Events Found in the last {{ query_window }}: {{ preemption_logs_parsed }}
      {% else %}
      No preemption events found for the checked instances in {{ deployment_name }} in the last {{ query_window }}.
      {% endif %}
