# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - region is defined
    - custom_vars.project is defined

- name: Get cluster credentials for kubectl
  delegate_to: localhost
  ansible.builtin.command: gcloud container clusters get-credentials {{ deployment_name }} --region {{ region }} --project {{ custom_vars.project }} --verbosity=debug

- name: Execute the job
  delegate_to: localhost
  ansible.builtin.shell: |
    array=({{ workspace }}/{{ deployment_name }}/primary/my-job*)
    kubectl create -f ${array[0]} -v=9
  args:
    executable: /bin/bash
  changed_when: False

- name: Block to wait for job completion and capture failures
  block:
  - name: Wait for job to complete
    delegate_to: localhost
    ansible.builtin.shell: |
      JOB_NAME=$(kubectl get job -o jsonpath='{.items[0].metadata.name}')
      kubectl wait --for=condition=complete "job/${JOB_NAME}" --timeout=10m
    args:
      executable: /bin/bash
  rescue:
  - name: "FAILURE: Job did not complete. Capturing debug info."
    ansible.builtin.debug:
      msg: "The Job failed to complete within the expected time. See debug output below."

  - name: Get all pods status on failure
    delegate_to: localhost
    ansible.builtin.shell: |
      kubectl get pods -o wide
    register: pods_on_failure
    changed_when: false

  - name: Print all pods status on failure
    ansible.builtin.debug:
      msg: "{{ pods_on_failure.stdout_lines }}"

  - name: Describe the job on failure
    delegate_to: localhost
    ansible.builtin.shell: |
      kubectl describe job
    register: job_describe_on_failure
    changed_when: false

  - name: Print job description on failure
    ansible.builtin.debug:
      msg: "{{ job_describe_on_failure.stdout_lines }}"

  - name: Get pod name on failure
    delegate_to: localhost
    ansible.builtin.shell: |
      kubectl get pods --selector=job-name --no-headers -o custom-columns=":metadata.name"
    register: pod_name_on_failure
    changed_when: false

  - name: Describe the pod on failure
    delegate_to: localhost
    ansible.builtin.shell: |
      kubectl describe pod {{ item }}
    loop: "{{ pod_name_on_failure.stdout_lines }}"
    register: pod_describe_on_failure
    changed_when: false
    when: pod_name_on_failure.stdout_lines | length > 0

  - name: Print pod description on failure
    ansible.builtin.debug:
      msg: "{{ pod_describe_on_failure.results }}"
    when: pod_name_on_failure.stdout_lines | length > 0

  - name: Get logs from the pod on failure
    delegate_to: localhost
    ansible.builtin.shell: |
      kubectl logs {{ item }}
    loop: "{{ pod_name_on_failure.stdout_lines }}"
    register: pod_logs_on_failure
    changed_when: false
    when: pod_name_on_failure.stdout_lines | length > 0

  - name: Print pod logs on failure
    ansible.builtin.debug:
      msg: "{{ pod_logs_on_failure.results }}"
    when: pod_name_on_failure.stdout_lines | length > 0

  - name: Fail the playbook
    ansible.builtin.fail:
      msg: "GKE Job did not complete successfully."

- name: Print job_completion debug output
  ansible.builtin.debug:
    var: job_completion.stdout_lines

- name: Clean up
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl delete job --all -v=9
