# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: "Multigroup integration test for gcluster deploy command"
  hosts: localhost
  force_handlers: true
  vars:
    delete_image: true
  tasks:
  - name: Create Deployment Directory
    ansible.builtin.include_tasks:
      file: tasks/create_deployment_directory.yml
  - name: Deploy from deployment directory
    block:
    - name: Execute gcluster deploy
      register: deployment
      changed_when: deployment.changed
      ansible.builtin.command: ./gcluster deploy {{ deployment_name }} --auto-approve
      args:
        chdir: "{{ workspace }}"
      environment:
        TF_IN_AUTOMATION: "TRUE"
    always:
    - name: Destroy deployment
      register: gcluster_destroy
      changed_when: gcluster_destroy.changed
      ignore_errors: true
      ansible.builtin.command: ./gcluster destroy {{ deployment_name }} --auto-approve
      args:
        chdir: "{{ workspace }}"
      environment:
        TF_IN_AUTOMATION: "TRUE"
    - name: Delete VM Image
      register: image_deletion
      changed_when: image_deletion.changed
      ignore_errors: true
      ansible.builtin.shell: |
        set -e -o pipefail
        gcloud compute images delete --project={{ project }} --quiet $(jq -r '.builds[-1].artifact_id' packer-manifest.json | cut -d ":" -f2)
      args:
        chdir: "{{ workspace }}/{{ deployment_name }}/{{ packer_group_name }}/{{ packer_module_id }}"
        executable: /bin/bash
      when:
      - delete_image | bool
      - packer_group_name is defined
      - packer_module_id is defined
    - name: Trigger Cloud Build failure
      when: gcluster_destroy is failed or image_deletion is failed
      ansible.builtin.fail:
        msg: "Failed while destroying deployment or deleting custom VM image"
