# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - blueprint_yaml is defined
    - project is defined
    - workspace is defined
    - deployment_name is defined
    - test_name is defined

- name: Set bucket
  ansible.builtin.set_fact:
    state_bucket: daily-tests-tf-state

- name: Create cli flag for extra deployment variables
  ansible.builtin.set_fact:
    deployment_vars_str: "--vars \"\\\"{{ cli_deployment_vars.items() | map('join', '=') | join('\\\"\" --vars \"\\\"') }}\\\"\""
  when: cli_deployment_vars is defined and cli_deployment_vars is mapping

- name: Create Blueprint
  ansible.builtin.command: |
      ./ghpc create -l ERROR "{{ blueprint_yaml }}" \
      --backend-config bucket={{ state_bucket }} \
      --skip-validators=test_tf_version_for_slurm \
      --vars project_id={{ project }} \
      --vars deployment_name={{ deployment_name }} \
      {{ deployment_vars_str if deployment_vars_str is defined else '' }}
  args:
    creates: "{{ workspace }}/{{ deployment_name }}"
    chdir: "{{ workspace }}"

- name: Compress Blueprint
  ansible.builtin.command:
    cmd: tar -czf "{{ deployment_name }}.tgz" "{{ deployment_name }}"
    creates: "{{ workspace }}/{{ deployment_name }}.tgz"
    chdir: "{{ workspace }}"
  tags:
  - skip_ansible_lint

- name: Uploading deployment
  ansible.builtin.command:
    cmd: gsutil cp "{{ deployment_name }}.tgz" "gs://{{ state_bucket }}/{{ test_name }}/"
    chdir: "{{ workspace }}"
  changed_when: True

- name: Print download command
  ansible.builtin.debug:
    msg: gcloud storage cp gs://{{ state_bucket }}/{{ test_name }}/{{ deployment_name }}.tgz .
