# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Gather instance information
  delegate_to: localhost
  when: deployment_name is defined and deployment_name | string
  changed_when: false
  register: instances
  until: instances.rc == 0
  retries: 5
  delay: 10
  ansible.builtin.command: >-
    gcloud compute instances list
    --filter="labels.ghpc_deployment={{ deployment_name }}"
    --format='json(name,zone,id,status)'
- name: Print instance information
  when: instances is defined
  ansible.builtin.debug:
    var: instances.stdout
- name: Print Cloud Logging command
  when: instances is defined and instances.stdout | list
  ansible.builtin.debug:
    msg: gcloud logging --project {{ project }} read 'logName="projects/{{ project }}/logs/google_metadata_script_runner" AND resource.labels.instance_id="{{ item.id }}"' --format="table(timestamp, jsonPayload.message)" --freshness 24h | tac
  loop: "{{ instances.stdout }}"
