# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# If using GCS as a terraform backend (suggested), add the following.  If not,
# comment out or remove.
terraform_backend_defaults:
  type: gcs
  configuration:
    bucket:  # Name of terraform state bucket.
# End of optional section

vars:
  deployment_name:  # Unique name of this Cluster Toolkit Deployment, e.g. a3u-gcs
  project_id:  # Your GCP project name
  region:  # e.g. europe-west1
  zone:  # e.g. europe-west1-b
  a3u_reservation_name:  # reservation name, e.g. a3u-reservation-00
  a3u_cluster_size:  # Number of A3-Ultra nodes in the cluster
  hns_gcs_bucket:  # This bucket must have been previously created
